version: '3.8'

# Network isolation
networks:
  live-chat-network:
    driver: bridge

services:
  backend:
    build:
      dockerfile: Dockerfile
    container_name: backend_test
    environment:
      - PYTHONPATH=/code
      - FLASK_APP=app.py
      - REDIS_HOST=redis
      - REDIS_PASSWORD=test_redispassword
      - MONGO_URI=mongodb://admin:admin1234@mongo:27017/chat_db
    depends_on:
      - redis
      - mongo
    networks:
      - live-chat-network
    command: >
      /bin/sh -c "
      while ! nc -z redis 6379; do
        echo 'Waiting for Redis...';
        sleep 1;
      done;
      while ! nc -z mongo 27017; do
        echo 'Waiting for MongoDB...';
        sleep 1;
      done;
      pytest tests/ --cov=app --cov-report=term-missing"

  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server --requirepass test_redispassword
    environment:
      - REDIS_PASSWORD=test_redispassword
    networks:
      - live-chat-network

  mongo:
    image: dannyben/alpine-mongo
    container_name: mongo
    environment:
      - MONGO_INITDB_DATABASE=chat_db
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin1234
    networks:
      - live-chat-network
