# this yaml file is intended to be used after development, to test the compose environment running all 4 containers locally mimicing the production enviironment

version: '3.8'

networks:
  live-chat-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
  redis-data:
    driver: local

services:
  backend:
    build:
      dockerfile: Dockerfile
    container_name: backend
    environment:
      - FLASK_APP=app.py
    networks:
      - live-chat-network
    ports:
      - 5000:5000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"
    networks:
      - live-chat-network

  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - live-chat-network
    volumes:
      - redis-data:/data

  mongo:
    image: dannyben/alpine-mongo
    container_name: mongo
    networks:
      - live-chat-network
    volumes:
      - mongo-data:/data/db