# this yaml file is to be used during developement to have redis and mongo containers for development purposes

version: '3.8'

networks:
  live-chat-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
  redis-data:
    driver: local

services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - live-chat-network
    volumes:
      - redis-data:/data

  mongo:
    image: dannyben/alpine-mongo
    container_name: mongo
    ports:
      - 27017:27017
    networks:
      - live-chat-network
    volumes:
      - mongo-data:/data/db