# production yaml

version: '3.8'

networks:
  live-chat-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
  redis-data:
    driver: local

services:
  backend:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${BACKEND_ECR}:${IMAGE_TAG}
    container_name: backend
    environment:
      - FLASK_APP=app.py
    networks:
      - live-chat-network
    ports:
      - 5000:5000

  frontend:
    image: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${FRONTEND_ECR}:${IMAGE_TAG}"
    container_name: frontend
    ports:
      - "5173:5173"
    networks:
      - live-chat-network

  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - live-chat-network
    volumes:
      - redis-data:/data

  mongo:
    image: dannyben/alpine-mongo
    container_name: mongo
    networks:
      - live-chat-network
    volumes:
      - mongo-data:/data/db